### ISSUE TITLE
"how are you" raised an error.

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/skill-ovos-hello-world#17]
```
Mar 29 12:01:00 neon ovos-core[879]: 2024-03-29 12:01:00.598 - skill-ovos-hello-world.openvoiceos - ERROR - 'str' object is not callable
Mar 29 12:01:00 neon ovos-core[879]: Traceback (most recent call last):
Mar 29 12:01:00 neon ovos-core[879]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/ovos_utils/events.py", line 78, in wrapper
Mar 29 12:01:00 neon ovos-core[879]:     handler(message)
Mar 29 12:01:00 neon ovos-core[879]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/skill_ovos_hello_world/__init__.py", line 82, in handle_how_are_you_intent
Mar 29 12:01:00 neon ovos-core[879]:     LOG.info(("There are five types of log messages: 'info, debug, warning, ")
Mar 29 12:01:00 neon ovos-core[879]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 29 12:01:00 neon ovos-core[879]: TypeError: 'str' object is not callable
```

**Comment by goldyfruit** [comment]
Fixed
